-- MySQL Script generated by MySQL Workbench
-- Fri Nov 15 09:56:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema opticalshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema opticalshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `opticalshop` DEFAULT CHARACTER SET utf8 ;
USE `opticalshop` ;

-- -----------------------------------------------------
-- Table `opticalshop`.`PHONEDETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`PHONEDETAILS` (
  `id_phonedetails` INT NOT NULL AUTO_INCREMENT,
  `Telephone` VARCHAR(20) NOT NULL,
  `Fax` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_phonedetails`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`ADRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`ADRESSES` (
  `id_address` INT NOT NULL AUTO_INCREMENT,
  `street_name` VARCHAR(45) NOT NULL,
  `street_number` VARCHAR(5) NOT NULL,
  `floor` VARCHAR(5) NULL,
  `door` VARCHAR(3) NULL,
  `postcode` VARCHAR(10) NOT NULL DEFAULT 'Barcelona',
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) GENERATED ALWAYS AS ('Spain'),
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`PROVIDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`PROVIDERS` (
  `id_provider` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(55) NOT NULL,
  `provider_addressID` INT NOT NULL,
  `provider_phonedetailsID` INT NOT NULL,
  `VAT Number` VARCHAR(15) NULL,
  PRIMARY KEY (`id_provider`),
  INDEX `phonedetailsID_idx` (`provider_phonedetailsID` ASC) VISIBLE,
  INDEX `addressID_idx` (`provider_addressID` ASC) VISIBLE,
  CONSTRAINT `provider_phonedetailsID`
    FOREIGN KEY (`provider_phonedetailsID`)
    REFERENCES `opticalshop`.`PHONEDETAILS` (`id_phonedetails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `provider_addressID`
    FOREIGN KEY (`provider_addressID`)
    REFERENCES `opticalshop`.`ADRESSES` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`BRANDS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`BRANDS` (
  `id_brand` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `providerID` INT NOT NULL,
  PRIMARY KEY (`id_brand`),
  INDEX `providerID_idx` (`providerID` ASC) VISIBLE,
  CONSTRAINT `providerID`
    FOREIGN KEY (`providerID`)
    REFERENCES `opticalshop`.`PROVIDERS` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`COLORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`COLORS` (
  `id_color` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_color`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`MOUNTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`MOUNTS` (
  `id_mount` INT NOT NULL AUTO_INCREMENT,
  `mount_type` VARCHAR(45) NOT NULL,
  `mountcolorID` INT NOT NULL,
  PRIMARY KEY (`id_mount`),
  INDEX `colorID_idx` (`mountcolorID` ASC) VISIBLE,
  CONSTRAINT `mountcolorID`
    FOREIGN KEY (`mountcolorID`)
    REFERENCES `opticalshop`.`COLORS` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`LENSE_PAIRS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`LENSE_PAIRS` (
  `id_lensepairs` INT NOT NULL AUTO_INCREMENT,
  `left_graduation` DECIMAL(4) NULL,
  `righ_graduation` DECIMAL(4) NOT NULL,
  `lensecolorID` INT NULL,
  PRIMARY KEY (`id_lensepairs`),
  INDEX `colorID_idx` (`lensecolorID` ASC) VISIBLE,
  CONSTRAINT `lensecolorID`
    FOREIGN KEY (`lensecolorID`)
    REFERENCES `opticalshop`.`COLORS` (`id_color`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`MODELS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`MODELS` (
  `id_model` INT NOT NULL AUTO_INCREMENT,
  `brandID` INT NOT NULL,
  `mountID` INT NOT NULL,
  `lensepairsID` INT NOT NULL,
  `price` DECIMAL(2) NULL,
  PRIMARY KEY (`id_model`),
  INDEX `brandID_idx` (`brandID` ASC) VISIBLE,
  INDEX `mountID_idx` (`mountID` ASC) VISIBLE,
  INDEX `lensepairsID_idx` (`lensepairsID` ASC) VISIBLE,
  CONSTRAINT `brandID`
    FOREIGN KEY (`brandID`)
    REFERENCES `opticalshop`.`BRANDS` (`id_brand`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mountID`
    FOREIGN KEY (`mountID`)
    REFERENCES `opticalshop`.`MOUNTS` (`id_mount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `lensepairsID`
    FOREIGN KEY (`lensepairsID`)
    REFERENCES `opticalshop`.`LENSE_PAIRS` (`id_lensepairs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`CLIENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`CLIENTS` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `client_addressid` INT NOT NULL,
  `client_telephoneid` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `referencerID` INT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `addressID_idx` (`client_addressid` ASC) VISIBLE,
  INDEX `telephoneID_idx` (`client_telephoneid` ASC) VISIBLE,
  INDEX `referencerID_idx` (`referencerID` ASC) VISIBLE,
  CONSTRAINT `client_addressID`
    FOREIGN KEY (`client_addressid`)
    REFERENCES `opticalshop`.`ADRESSES` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `client_telephoneID`
    FOREIGN KEY (`client_telephoneid`)
    REFERENCES `opticalshop`.`PHONEDETAILS` (`id_phonedetails`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `referencerID`
    FOREIGN KEY (`referencerID`)
    REFERENCES `opticalshop`.`CLIENTS` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`SELLERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`SELLERS` (
  `id_seller` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `opticalshop`.`INVOICES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`INVOICES` (
  `id_invoice` INT NOT NULL AUTO_INCREMENT,
  `sellerID` INT NOT NULL,
  `clientID` INT NOT NULL,
  `total` DECIMAL(2) NOT NULL,
  `modelID` INT NOT NULL,
  PRIMARY KEY (`id_invoice`),
  INDEX `sellerID_idx` (`sellerID` ASC) VISIBLE,
  INDEX `clientID_idx` (`clientID` ASC) VISIBLE,
  INDEX `modelID_idx` (`modelID` ASC) VISIBLE,
  CONSTRAINT `sellerID`
    FOREIGN KEY (`sellerID`)
    REFERENCES `opticalshop`.`SELLERS` (`id_seller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `clientID`
    FOREIGN KEY (`clientID`)
    REFERENCES `opticalshop`.`CLIENTS` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `modelID`
    FOREIGN KEY (`modelID`)
    REFERENCES `opticalshop`.`MODELS` (`id_model`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `opticalshop` ;

-- -----------------------------------------------------
-- Placeholder table for view `opticalshop`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `opticalshop`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `opticalshop`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `opticalshop`.`view1`;
USE `opticalshop`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
